@isTest
private class PassengerToAccountReplicatorTest {
/*
	static Account a;
	static Passenger__c p;

	@isTest static void testDataIsReplicated()
	{
		setup();
		Test.startTest();
		p.Family_Name__c = 'Jong-Un';
		update p;
		Test.stopTest();
		System.assertEquals(p.Family_Name__c, [SELECT LastName FROM Account WHERE Id =: a.Id].LastName);
	}

	static void setup()
	{
		a = new Account();
		a.FirstName = 'Kim';
		a.LastName = 'Jong-Il';
		insert a;

		p = new Passenger__c();
		p.Name = 'Kim';
		p.Family_Name__c = 'Jong-Il';
		p.Account__c = a.id;
		p.Passenger_External_Id__c = '123245674123';
		p.Passenger_Class__c = 'Passenger';
		insert p;

	}
*/
}